backend:
  name: github
  repo: JakeSchroeder/jakeschroeder.me

publish_mode: editorial_workflow

media_folder: static/assets/uploads
public_folder: /assets/uploads
site_url: https://jakeschroeder.me

collections:
  - name: Section
    label: Blog
    folder: content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }